# Project: Project_laba_4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = laba.o mylibc.o
LINKOBJ  = laba.o mylibc.o
LIBS     = -L"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/lib" -L"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/include" -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/include" -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/skyhu/Desktop/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project_laba_4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

laba.o: laba.c
	$(CC) -c laba.c -o laba.o $(CFLAGS)

mylibc.o: mylibc.c
	$(CC) -c mylibc.c -o mylibc.o $(CFLAGS)
